version: '3.8'
services:
  docker-playground:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/players
      - MYSQL_USER=user
      - MYSQL_PASS=password
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    # DON'T NEED TO SPECIFY NETWORK (COMPOSE ADD ALL SERVICES TO THE SAME NETWORK)
#    networks:
#      - net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=players
    volumes:
      - mysql-vol:/var/lib/mysql
volumes:
  mysql-vol: